routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('product', App\Http\Controllers\ProductController::class, 
      ['names' => 'product']
);

Route::resource('student', App\Http\Controllers\StudentController::class, 
      ['names' => 'student']
);

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory;
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Product;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $products = Product::all();
        return view('product.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('product.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required',
            'price' => 'required',
            'product_image' => 'required|image|mimes:jpeg,png,jpg',
            'description' => 'required',
        ]);

        if ($request->hasFile('product_image')) {
            $file = $request->file('product_image');
            $extension = $file->extension();
            $final = date('YmdHis').'.'.$extension;
            $file->move(public_path('/uploads'), $final);
        };

        $product = new Product();
        $product->title = $request->title;
        $product->price = $request->price;
        $product->product_image = $final;
        $product->description = $request->description;
        $product->save();

        return redirect()->route('product.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = Product::findOrFail($id);
        return view('product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $product = Product::findOrFail($id);

        if ($request->hasFile('product_image')) {
            if (file_exists(public_path('/uploads/'.$product->product_image))) {
                unlink(public_path('/uploads/'.$product->product_image));
            }

            $request->validate([
                'product_image' => 'required|image|mimes:jpeg,png,jpg'
            ]);

            $file = $request->file('product_image');
            $extension = $file->extension();
            $final = date('YmdHis').'.'.$extension;
            $file->move(public_path('/uploads'), $final);

            $product->product_image = $final;
        };

        $request->validate([
            'title' => 'required',
            'price' => 'required',
            'description' => 'required',
        ]);

        $product->title = $request->title;
        $product->price = $request->price;
        $product->description = $request->description;
        $product->update();

        return redirect()->route('product.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $product = Product::findOrFail($id);

        if (file_exists(public_path('/uploads/'.$product->product_image))) {
            unlink(public_path('/uploads/'.$product->product_image));
        }
        $product->delete();

        return redirect()->route('product.index');
    }
}

resources/views/product/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="mt-5 col-lg-8">
                <form action="{{ route('product.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                        <label for="productName" class="form-label">Product Name</label>
                        <input type="text" class="form-control" id="title" name="title" placeholder="Product Name">
                        @error('title')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="price" class="form-label">Product Price</label>
                        <input type="text" class="form-control" id="price" name="price"
                            placeholder="Product Price">
                        @error('price')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="image" class="form-label">Product Image</label>
                        <input type="file" class="form-control" id="product_image" name="product_image"
                            placeholder="Product Image">
                        @error('product_image')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Product Description</label>
                        <textarea class="form-control" id="description" name="description" placeholder="Product Description" rows="10"></textarea>
                        @error('description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/product/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="mt-5">
                <form action="{{ route('product.update', $product->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <label for="productName" class="form-label">Product Name</label>
                        <input type="text" value="{{ $product->title }}" class="form-control" id="title"
                            name="title" placeholder="Product Name">
                        @error('title')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="price" class="form-label">Product Price</label>
                        <input type="text" value="{{ $product->price }}" class="form-control" id="price"
                            name="price" placeholder="Product Price">
                        @error('price')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="image" class="form-label">Product Image</label>
                        <input type="file" class="form-control" id="product_image" name="product_image"
                            placeholder="Product Image">
                        @error('product_image')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <img src="{{ url('/uploads', $product->product_image) }}" alt="" width="120px"
                            height="120px">
                    </div>
                    <div class="mb-3">
                        <label for="description" class="form-label">Product Description</label>
                        <textarea class="form-control" id="description" name="description" placeholder="Product Description" rows="10">{{ $product->description }}</textarea>
                        @error('description')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/product/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Serial No.</th>
                    <th scope="col">Product Name</th>
                    <th scope="col">Price</th>
                    <th scope="col">Photo</th>
                    <th scope="col">Description</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($products as $product)
                    <tr>
                        <th scope="row">{{ $product->id }}</th>
                        <td>{{ $product->title }}</td>
                        <td>{{ $product->price }}</td>
                        <td>
                            <img src="{{ url('/uploads', $product->product_image) }}" alt="" width="80px"
                                height="80px">
                        </td>
                        <td>{{ $product->description }}</td>
                        <td>
                            <a class="btn btn-primary" href="{{ route('product.edit', $product->id) }}">Edit</a>
                            <form action="{{ route('product.destroy', $product->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection