routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('product', App\Http\Controllers\ProductController::class, 
      ['names' => 'product']
);

Route::resource('student', App\Http\Controllers\StudentController::class, 
      ['names' => 'student']
);

app/Models/Student.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Student extends Model
{
    use HasFactory;
}

app/Http/Controllers/StudentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Models\Student;

use Image;


class StudentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $students = Student::all();
        return view('student.index', compact('students'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('student.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required',
            'student_id' => 'required|numeric',
            'student_img' => 'required|image|mimes:jpeg,png,jpg|max:2048',
        ]);

        if ($request->hasFile('student_img')) {
            $file = $request->file('student_img');
            $extension = $file->extension();
            $final = date('YmdHis').'.'.$extension;

            Image::make($file)->resize(200, 200)->save(public_path('/uploads/').$final);
        };

        $student = new Student();
        $student->name = $request->name;
        $student->student_id = $request->student_id;
        $student->student_img = $final;
        $student->save();

        return redirect()->route('student.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $student = Student::findOrFail($id);
        return view('student.edit', compact('student'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $student = Student::findOrFail($id);

        if ($request->hasFile('student_img')) {
            if (file_exists(public_path('/uploads/'.$student->student_img))) {
                unlink(public_path('/uploads/'.$student->student_img));
            }

            $request->validate([
                'student_img' => 'required|image|mimes:jpeg,png,jpg|max:2048',
            ]);

            $file = $request->file('student_img');
            $extension = $file->extension();
            $final = date('YmdHis').'.'.$extension;

            // Image::make($file)->resize(100, 100)->insert(name/name.png, 'bottom')->save(public_path('/uploads/').$final);
            Image::make($file)->resize(100, 100)->save(public_path('/uploads/').$final);

            $student->student_img = $final;
        }

        $request->validate([
            'name' => 'required',
            'student_id' => 'required|numeric',
        ]);

        $student->name = $request->name;
        $student->student_id = $request->student_id;
        $student->update();

        return redirect()->route('student.index');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $student = Student::findOrFail($id);

        if (file_exists(public_path('/uploads/'.$student->student_img))) {
            unlink(public_path('/uploads/'.$student->student_img));
        }
        $student->delete();

        return redirect()->route('student.index');
    }
}

resources/views/student/create.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="mt-5 col-lg-8">
                <form action="{{ route('student.store') }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="mb-3">
                        <label for="studentName" class="form-label">Student Name</label>
                        <input type="text" class="form-control" id="name" name="name" placeholder="Student Name">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="student-id" class="form-label">Student ID</label>
                        <input type="text" class="form-control" id="student_id" name="student_id"
                            placeholder="Student ID">
                        @error('student_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="student-img" class="form-label">Product Image</label>
                        <input type="file" class="form-control" id="student_img" name="student_img"
                            placeholder="Student Image">
                        @error('student_img')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>

                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Add</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/student/edit.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <div class="row">
            <div class="mt-5">
                <form action="{{ route('student.update', $student->id) }}" method="POST" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <div class="mb-3">
                        <label for="productName" class="form-label">Student Name</label>
                        <input type="text" value="{{ $student->name }}" class="form-control" id="name" name="name"
                            placeholder="Student Name">
                        @error('name')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="student-id" class="form-label">Product Price</label>
                        <input type="text" value="{{ $student->student_id }}" class="form-control" id="student_id"
                            name="student_id" placeholder="Student ID">
                        @error('student_id')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <label for="image" class="form-label">Student Image</label>
                        <input type="file" class="form-control" id="student_img" name="student_img"
                            placeholder="Student Image">
                        @error('student_img')
                            <span class="text-danger">{{ $message }}</span>
                        @enderror
                    </div>
                    <div class="mb-3">
                        <img src="{{ url('/uploads', $student->student_img) }}" alt="">
                    </div>
                    <div class="mb-3">
                        <button type="submit" class="btn btn-primary">Edit</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/student/index.blade.php
@extends('layouts.master')

@section('content')
    <div class="container">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Serial No.</th>
                    <th scope="col">Student Name</th>
                    <th scope="col">Student ID</th>
                    <th scope="col">Student Image</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($students as $student)
                    <tr>
                        <th scope="row">{{ $student->id }}</th>
                        <td>{{ $student->name }}</td>
                        <td>{{ $student->student_id }}</td>
                        <td>
                            <img src="{{ url('/uploads', $student->student_img) }}" alt="">
                        </td>
                        <td>
                            <a class="btn btn-primary" href="{{ route('student.edit', $student->id) }}">Edit</a>
                            <form action="{{ route('student.destroy', $student->id) }}" method="POST">
                                @csrf
                                @method('DELETE')
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
@endsection